input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
  }
}

output {
     if ( [tag] == "nginx" ) {
       elasticsearch {
         hosts => [ "${ES_HOST}" ]
         index => "nginx-%{+YYYY.MM.dd}"
       }
   }
   else if ( [tag] == "etl_user_events" ) {
       elasticsearch {
         hosts => [ "${ES_HOST}" ]
         index => "etl_user_events-%{+YYYY.MM.dd}"
       }
   }
   else if ( [tag] == "fastapi_app" ) {
       elasticsearch {
         hosts => [ "${ES_HOST}" ]
         index => "fastapi_app-%{+YYYY.MM.dd}"
       }
   }
  stdout { codec => rubydebug }
}