filebeat.inputs:
  - type: filestream
    id: fastapi-logs
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container: ~

processors:
  processors:

    - add_docker_metadata: ~

    - add_fields:
        when:
          contains:
            container.name: "nginx"
        target: ""
        fields:
          tag: "nginx"

    - add_fields:
        when:
          contains:
            container.name: "etl-user-events"
        target: ""
        fields:
          tag: "etl_user_events"

    - add_fields:
        when:
          or:
            - contains:
                container.name: "fastapi"
        target: ""
        fields:
          tag: "fastapi_app"

output.logstash:
  hosts: ["logstash:5044"]